apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: oi9x8avtp-go 
  janus-idp.io/tekton: oi9x8avtp-go
  backstage.io/kubernetes-id: oi9x8avtp-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: oi9x8avtp-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml