apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: oi9x8avtp-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: oi9x8avtp-go 
  name: oi9x8avtp-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: oi9x8avtp-go 
